POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2MTViNDAwYWU4ZmNiNzJmNDI2NzI5NzciLCJpYXQiOjE2MzM0NzI5ODd9.a0jpAY9JZPKv6m3aJ77TwT19z16YWZqG-C7sVgu3Y2I

{
    "title": "with token aaa",
    "author": "with token aaa", 
    "url": "with token aaa",
    "likes": 2343
}

###

DELETE http://localhost:3003/api/blogs/615c8bafda6ea3a5e9a76941 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2MTViM2YxNGI0YzQ4YWFlNmIyOTYwNzkiLCJpYXQiOjE2MzM0NzIxNjh9.i-vpov9EEG5imtJVV0iYcexKB0URm49oNX8Boqq1v74

###

PUT http://localhost:3003/api/blogs/615645e0c0f1ddf7214f1592 HTTP/1.1
content-type: application/json

{
    "author": "updated author"
}

### 
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "name": "user2 name",
    "username": "user2", 
    "password": "pas"
}

### 
POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
    "username": "user2", 
    "password": "pass"
}