POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "new title",
    "author": "new author", 
    "url": "url new new new",
    "likes": 6235
}

###

DELETE http://localhost:3003/api/blogs/615645ecc0f1ddf7214f1595 HTTP/1.1

###

PUT http://localhost:3003/api/blogs/615645e0c0f1ddf7214f1592 HTTP/1.1
content-type: application/json

{
    "author": "updated author"
}

### 
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "name": "user2 name",
    "username": "user2", 
    "password": "pas"
}